### ISSUE TITLE
Feature request: display svg instead of icon

### ISSUE THREAD

**Issue by tomei64** [AmoebeLabs/flex-horseshoe-card#102]
I use the card to e.g. display the status of our cars, electric and hybrid. It would be good to easily distinguish by picture displayed instead of standard icon, but cannot find a way to do that. Could that be added (or has anybody an idea how to achieve myself)?

**Comment by AmoebeLabs** [comment]
Icons can have an URL, and an icon can have state-dependent icons (svg, image, mdi icon).

SVG as url (the pollen thingy):
```yaml
          entities:
            - entity: sensor.dsmr_reading_electricity_currently_delivered
              decimals: 2
              name: 'Electricity'
              area: ':35:'
              # icon: url(/local/icons/icon-test.png)
              icon: url(/local/images/tomorrow/pollen_grass_high.svg)
```

<img width="409" height="403" alt="Image" src="https://github.com/user-attachments/assets/48895169-11f4-4100-be67-f2c966926747" />

The full Kleenex Pollen Radar with states low, moderate, high, and very_high.
```yaml
              - entity_index: 2
                same_as: 1
                same_as_dxpos: calc(dxPos2)
                same_as_replace:
                  - state_map
                state_map:
                  map:
                    - state: 'low'
                      icon: url(/local/images/kleenex/pollen_weed_low.svg)
                    - state: 'moderate'
                      icon: url(/local/images/kleenex/pollen_weed_moderate.svg)
                    - state: 'high'
                      icon: url(/local/images/kleenex/pollen_weed_high.svg)
                    - state: 'very_high'
                      icon: url(/local/images/kleenex/pollen_weed_very_high.svg)
```

<img width="407" height="403" alt="Image" src="https://github.com/user-attachments/assets/b3dddece-6957-46d3-90f5-ce1eaa7475c7" />
