### ISSUE TITLE
entityConfig is undefined : the page is blank

### ISSUE THREAD

**Issue by clabnet** [AmoebeLabs/flex-horseshoe-card#15]
Hi, 
Hassio ver.  0.105.5  and   flex-horseshoe-card downloaded from HACS 1 hour ago.

The simple card is blank, no messages on log, on Developers Tools page : 
**flex-horseshoe-card.js:1703:1 TypeError: entityConfig is undefined**

Also your examples page is blank. Any help ? Thanks for your work.

```
id: tests
title: Test page
icon: 'mdi:battery-charging'
panel: true
path: test

cards:

  - type: vertical-stack
    cards:

    - !include
      - ../includes/titles.yaml
      - title: 'TEST'

    - type: custom:flex-horseshoe-card
      entities:
        - entity:  display.wall_tablet
          attribute: battery_level
          units: '%'
          icon: mdi:battery
          name: 'Batteria'              
        - entity:  display.wall_tablet
          attribute: battery_charging
          icon: mdi:battery-charging
          name: 'In carica'
      show:
        horseshoe_style: lineargradient          
      layout:
        hlines:
          - id: 0
            xpos: 50
            ypos: 42
            length: 40
            styles:
              - stroke: var(--primary-text-color);
              - stroke-width: 5;
              - stroke-linecap: round;
              - opacity: 0.7;
        states:
          - id: 0
            entity_index: 0
            xpos: 50
            ypos: 34
            styles:
              - font-size: 3em;
          - id: 1
            entity_index: 1
            xpos: 40
            ypos: 57
            styles:
              - text-anchor: start;
              - font-size: 1.5em;
        icons:
          - id: 0
            entity_index: 1
            xpos: 37
            ypos: 57
            align: end
            size: 1.3
          - id: 1
            entity_index: 2
            xpos: 37
            ypos: 72
            align: end
            size: 1.3
        names:
          - id: 0
            entity_index: 0
            xpos: 50
            ypos: 95

      horseshoe_scale:
        min: -10
        max: 40

      color_stops:
        16: '#FFF6E3'
        17: '#FFE9B9'
        18: '#FFDA8A'
        19: '#FFCB5B'
        20: '#FFBF37'
        21: '#ffb414'
        22: '#FFAD12'
        23: '#FFA40E'
        24: '#FF9C0B' 
        25: '#FF8C06' 


```
