### ISSUE TITLE
Not able to hide unit of measurement 

### ISSUE THREAD

**Issue by PhilippBaumgarten** [AmoebeLabs/flex-horseshoe-card#29]
Currently I couldn't find any option to disable the card to show the unit of measurement for an entity. I one card I'd like to show my download speeds, which is in combination with the mesaurement unit quite large for one line:
350 Mbit/s

I was not able to manually set the attribute unit to empty (e.g. `unit: ''`) or just leave the whole attribute out of code. In both cases the default measurement unit was chosen. I think following lines must be adapted to allow at least `unit: ''`:
https://github.com/AmoebeLabs/flex-horseshoe-card/blob/e09bb7b30228bd12dba3861fa0d3d5804e41ecc1/flex-horseshoe-card.js#L1719-L1725

**Expected solution:**

1.  Either the card should automatically wrap the unit to a next line
2. Offer a manual CSS option to wrap the unit to a next line
3. Deactivate the card to show the unit of measurement

**Comment by AmoebeLabs** [comment]
Supported by the latest versions.

You can style the uom as part of the states.
- colors
- fonts
- remove the uoam by defining `display: none;`

```yaml
          layout:
            states:
              - id: 0
                entity_index: 0
                xpos: 50
                ypos: 28
                styles:
                  - font-size: 2.5em;
                  - opacity: 0.9;
                uom:
                  styles:
                    - font-size: 1.5em;
                    - opacity: 0.5;
                    - fill: red;
                    - display: none;
```
