### ISSUE TITLE
Template sensors don't render. Nothing is shown in that case

### ISSUE THREAD

**Issue by AmoebeLabs** [AmoebeLabs/flex-horseshoe-card#3]
As shown in this post: https://community.home-assistant.io/t/lovelace-flexible-horseshoe-card-donut-graph-flexible-layout-multiple-entities-actions-animations-including-next-gen-experimental-examples/137850/47, template sensors using a value_template don't render.

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/b/8/b81b2193ae7f10e7b205a84a59145b66f294ed7b_2_690x423.jpeg)

Sensor is defined as:
```yaml
      esxi_vm0_datastore1_total_capacity:
        friendly_name: 'VM0 Used Disk Space - Datastore 1'
        value_template: "{{ states['sensor.esxi_datastore_datastore1'].attributes.total_space_gb + states['sensor.esxi_datastore_vms_datastore'].attributes.total_space_gb | round () }}"
        unit_of_measurement: 'GBs'
```
