### ISSUE TITLE
Horseshoe card doesn't work after update of HA to 2022.10.5

### ISSUE THREAD

**Issue by JaroslawPrzybyl** [AmoebeLabs/flex-horseshoe-card#58]
This card stop working after last update of HA.
Do you know this issue and is any fix available?

**Comment by Mediacj** [comment]
Same for me I reinstalled the card but still the same. I get this error:
"Custom element doesn't exist: flex-horseshoe-card."

**Comment by mhooghiemstra79** [comment]
Same here on my mobile devices. 
Strange thing is though on my nest hub where I use  dash cast to cast the same dashboard it works fine.

**Comment by AmoebeLabs** [comment]
I think that if you would check the console from Chrome you will see CORS errors.

My installation does NOT work anymore with the latest HA if I omit the  `cors_allowed_origins` 

HA currently needs the `cors_allowed_origins` to be set (https://www.home-assistant.io/integrations/http/)

FH needs some stuff from unkpg.com. My current list is:
```
http:
  server_port: 8123
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://unpkg.com
    - https://<my-ha-domain.com>
```

You can also use a CORS plugin for Chrome to test things:

![image](https://user-images.githubusercontent.com/7996307/198672366-036277f2-7540-47da-9528-41c0e5447262.png)

My test cards are still working with the latest HA:

![image](https://user-images.githubusercontent.com/7996307/198674566-9b1641e4-76e8-4256-90af-1ffd9348e39b.png)

![image](https://user-images.githubusercontent.com/7996307/198674353-84bc58a0-5f06-4d14-a01e-d24b91e90b72.png)

Let me know if the CORS errors are indeed the problem!
