### ISSUE TITLE
HACS Install not working correctly?

### ISSUE THREAD

**Issue by MVerBerkmoes** [AmoebeLabs/flex-horseshoe-card#72]
Installed card via Frontend.  Card shows in the list of Frontend cards, but does not show up in the list when adding card to a view.

Copy and pasted an example into a manual card and receive 'No card type configured'

flex-horseshoe-card.js has been installed in config\www\community\flex-horseshoe-card.

Reboot of HA changes nothing.

**Comment by darknessblade** [comment]
Having the exact same issue.

tried a older version of horseshoe, but those do not work either

**Comment by jeffrey-zammit** [comment]
Same here

**Comment by waltergradauer** [comment]
I just found this repository, I would have liked to try it, but it has a bug that probably doesn't work on version 2023.7.3

Too bad, I'm waiting for the bug fix

**Comment by nordgoth** [comment]
> Installed card via Frontend. Card shows in the list of Frontend cards, but does not show up in the list when adding card to a view.
> 
> Copy and pasted an example into a manual card and receive 'No card type configured'
> 
> flex-horseshoe-card.js has been installed in config\www\community\flex-horseshoe-card.
> 
> Reboot of HA changes nothing.

it actually does work even with 2023.8.1 however indentation are incorrect in the given example, try the following:

```

type: custom:flex-horseshoe-card
entities:
  - entity: weather.weather
    attribute: temperature
    decimals: 1
    unit: °C
    area: De Maan
show:
  horseshoe_style: lineargradient
layout:
  states:
    - id: 0
      entity_index: 0
      xpos: 50
      ypos: 60
      styles:
        - font-size: 3.5em;
  areas:
    - id: 0
      entity_index: 0
      xpos: 50
      ypos: 35
      styles:
        - font-size: 1.5em;
        - opacity: 0.8;
horseshoe_scale:
  min: -10
  max: 40
color_stops:
  '10': red
  '18': blue

```

<img width="253" alt="image" src="https://github.com/AmoebeLabs/flex-horseshoe-card/assets/53017119/079f2f44-f99e-4fe5-a813-4bd9bf629599">
