### ISSUE TITLE
calculated values as entities

### ISSUE THREAD

**Issue by turboc1208** [AmoebeLabs/flex-horseshoe-card#73]
How can I include a calculated value as an entity?  For example, brightness is on a scale of 0-255 I would like to show it as a percentage so brightness/255.

**Comment by AmoebeLabs** [comment]
The latest versions support conversion:

```yaml
            - entity: light.livingroom_light_duo_left_light
              name: Duo Links
              area: Woonkamer
              icon: mdi:floor-lamp-dual
              attribute: brightness
              convert: brightness_pct
```
