### ISSUE TITLE
tap event not working as expected on light

### ISSUE THREAD

**Issue by turboc1208** [AmoebeLabs/flex-horseshoe-card#74]
I have a light that I want to control.  The horseshoe will show the brightness while an icon will simply turn it on or off.  Clicking on the horseshoe will bring up the normal brightness/on/off control while clicking on the little fan-light icon should toggle it on or off.  At least that's what I want.  What's happening is that in either case, clicking just brings up the standard brightness/on/off control.
I have tried having the entity_id: light.office_light in both the service_data and in the target lists.  Same results both ways.  Any advice would be appreciated.

```
type: custom:flex-horseshoe-card
entities:
  - entity: light.office_light
    attribute: brightness
    decimals: 1
    unit: '%'
    area: Office
  - entity: light.office_light
    name: Light
    icon: mdi:ceiling-fan-light
    tap_action:
      action: call-service
      service: light.toggle
      service_data: 
      target:
        entity_id: light.office_light
        ```

**Comment by papperone** [comment]
I mainly use switches and it does work with code below:

```
  - entity: switch.microonde
    name: ' '
    icon: mdi:microwave
    tap_action:
      action: call-service
      service: switch.toggle
      service_data:
        entity_id: switch.microonde
```
