### ISSUE TITLE
No horseshoe scale defined

### ISSUE THREAD

**Issue by hermannw** [AmoebeLabs/flex-horseshoe-card#8]
I installed the card via HACS, added the URL to the lovelace resources and copied your basic example. All I see is "No horseshoe scale defined". After removing various elements to see if other messages show up, I ended with this:
```
      - type: 'custom:flex-horseshoe-card'
        entities:
          - entity: weather.dark_sky
            attribute: temperature
            decimals: 1
            unit: °C
            area: De Maan
        layout:
          horseshoe_scale:
            min: -10
            max: 40
```
![image](https://user-images.githubusercontent.com/5613181/71608437-f7018b00-2b46-11ea-90c9-bec7627c5b7e.png)

I am using HA V0.102.2 and the build in lovelace editor. I'm not using the decluttering card...

**Comment by vaidyasr** [comment]
The indention of the horseshoe_scale should be one level up along with the entities. It should be
```
type: 'custom:flex-horseshoe-card'
entities:
  - entity: xxxx
    attribute: xxxx
    decimals: 1
    unit: xx
    area: xxxx
horseshoe_scale:
  min: -10
  max: 40
```
