### ISSUE TITLE
Customer elements doesn't exist

### ISSUE THREAD

**Issue by glemag** [AmoebeLabs/flex-horseshoe-card#97]
After last updated card crashed, tried to reinstall - no luck

Core
2024.11.1
Supervisor
2024.11.2
Operating System
13.2
![2024-11-14_17-57-54](https://github.com/user-attachments/assets/0bdddcc7-71d4-4c4d-ab59-183021428559)

**Comment by Marmoulak** [comment]
same problem after upgrade to Core 2014.12.1. I have remove it and  download it again but did not help. 
 Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6

**Comment by Kratax** [comment]
I have the same issue with HA 2024.11.3, seems it stopped working... re-download not working

**Comment by Duncan1106** [comment]
I had the same issue with this and another custom card. Here’s what I did to resolve it:

1. Removed it in HACS so that it was no longer installed.

2. Rebooted the system.

3. Re-added it, and it worked again.

Hopefully, this helps someone!

I'm running:
Core: 2024.12.1
Supervisor: 2024.11.4
Operating System: 14.0
Frontend: 20241127.6

**Comment by Kratax** [comment]
Worked as well, thanks!

**Comment by Marmoulak** [comment]
its working again. Thanks @Duncan1106

**Comment by Miloux99** [comment]
I have 2025.1 installed.
I'm unable to get this card on the dashboard.
Errormessage is Custom element doesn't exist: flexible-horseshoe-card.
Has anybody a hint?

**Comment by Duncan1106** [comment]
@Miloux99 have you tried my method from above?

**Comment by boulete31** [comment]
same here, trick above doesn't work.


<img width="1005" alt="Capture d’écran 2025-01-08 à 14 39 25" src="https://github.com/user-attachments/assets/e5cbde0e-898d-45ce-b2af-b850f25483fe" />

**Comment by Duncan1106** [comment]
@boulete31 
It appears your error is different from ours.
Your code seems to function I've tested it on my system:

```
type: custom:flex-horseshoe-card
entities:
    - entity: sensor.kaffee_temperature
      decimals: 1
      unit: °C
      area: De Maan
show:
    horseshoe_style: 'lineargradient'
layout:
    states:
     - id: 0
       entity_index: 0
       xpos: 50
       ypos: 60
       styles:
        - font-size: 3.5em;
    areas:
     - id: 0
       entity_index: 0
       xpos: 50
       ypos: 35
       styles:
        - font-size: 1.5em;
        - opacity: 0.8;
horseshoe_scale:
    min: 10
    max: 40
color_stops:
    10 : 'red'
    18 : 'blue'
```

I don't know what you could do differently. I'm not very good with this card...

At the bottom you have another error, maybe your attribute is typed wrong or something like that? Maybe you want to access the state of the entity directly and not an attribute of it? If so remove line 4:  

```
attribute: temperature
```

If your adding it via Manual card remove the " - " before the type and move the type at the very beginning of the line. If I copy it directly out I get the same error as yours, but if the type is at the very beginning it does function properly, also move the lines: show, layout, horseshoe_scale and color_stops at the very beginning of each corresponding line.

If all of the above isn't helping:
Try to clear your browser cache or of the Homeassistant app and completely reboot the Homeassistant system, if that's not helping I don't know what to do.
